### ISSUE TITLE
Compiler crash during zing generation

### ISSUE THREAD

**Issue by paulthomson** [p-org/P#12]
The following causes a `KeyNotFoundException` when generating the zing model.

crash.p:
```
module MyModule
{

main machine Manager {


    start state Init
    {
        entry
        {
            send this, halt;
        }
    }

}
}

test crash: MyModule;
implementation MyModule;
```

```
D:\pazure\testing>pc crash.p
Writing stubs.c ...
Writing program.h ...
Writing program.c ...

Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Pc.PToZing.TypeTranslationContext.ConstructType(FuncTerm type) in d:\pazure\P\Src\Pc\Compiler\PToZing.cs:line 4263
   at Microsoft.Pc.PToZing.TypeTranslationContext.PTypeToZingExpr(FuncTerm pType) in d:\pazure\P\Src\Pc\Compiler\PToZing.cs:line 4256
   at Microsoft.Pc.PToZing.FoldNulApp(FuncTerm ft, IEnumerable`1 children, ZingFoldContext ctxt) in d:\pazure\P\Src\Pc\Compiler\PToZing.cs:line 3273
   at Microsoft.Pc.PToZing.ZingFold(ZingFoldContext ctxt, Node n, IEnumerable`1 children) in d:\pazure\P\Src\Pc\Compiler\PToZing.cs:line 2855
   at Microsoft.Pc.PToZing.<>c__DisplayClass53.<MkZingFunMethod>b__52(Node x, IEnumerable`1 ch) in d:\pazure\P\Src\Pc\Compiler\PToZing.cs:line 3956
   at Microsoft.Formula.API.ASTComputation`1.Compute()
   at Microsoft.Formula.API.ASTConcr`1.Compute[S](Func`2 unfold, Func`3 fold, CancellationToken cancel)
   at Microsoft.Pc.PToZing.MkZingFunMethod(String machineName, String funName, FunInfo funInfo) in d:\pazure\P\Src\Pc\Compiler\PToZing.cs:line 3954
   at Microsoft.Pc.PToZing.GenerateMachineClass(String machineName) in d:\pazure\P\Src\Pc\Compiler\PToZing.cs:line 2080
   at Microsoft.Pc.PToZing.MkZingClasses(List`1 elements) in d:\pazure\P\Src\Pc\Compiler\PToZing.cs:line 2098
   at Microsoft.Pc.PToZing.GenerateZing(List`1& FileNames, AST`1& outModel) in d:\pazure\P\Src\Pc\Compiler\PToZing.cs:line 1687
   at Microsoft.Pc.Compiler.GenerateZing(List`1 flags) in d:\pazure\P\Src\Pc\Compiler\Compiler.cs:line 412
   at Microsoft.Pc.Compiler.Compile(String inputFileName, List`1& flags) in d:\pazure\P\Src\Pc\Compiler\Compiler.cs:line 378
   at Microsoft.Pc.Compiler.Compile(String inputFileName) in d:\pazure\P\Src\Pc\Compiler\Compiler.cs:line 42
   at Microsoft.Pc.CommandLine.Main(String[] args) in d:\pazure\P\Src\Pc\CommandLine\CommandLine.cs:line 85
```

**Comment by paulthomson** [comment]
Only on the modp branch, I think.

**Comment by desaiankush** [comment]
I have fixed this bug.
P\Tst\RegressionTests\Feature1SMLevelDecls\DynamicError\Halt
