### ISSUE TITLE
Possible Bug in Monitor Translation to P#

### ISSUE THREAD

**Issue by suvamM** [p-org/P#196]
On compiling the `PingPong` sample to `P#`, I kept hitting the following error during testing:

`Error: Exception 'System.Reflection.TargetInvocationException' was thrown in test method 'PingPongApp.Test0.Execute', 'Microsoft.PSharp.TestingServices':
   Exception has been thrown by the target of an invocation.
The stack trace is:
   at Microsoft.PSharp.TestingServices.TestHarnessMachine.Run() in C:\Users\t-sumukh\source\repos\vsc\PSharp\Source\TestingServices\Runtime\TestHarnessMachine.cs:line 62
   at Microsoft.PSharp.TestingServices.TestingRuntime.<>c__DisplayClass34_0.<RunTestHarness>b__0() in C:\Users\t-sumukh\source\repos\vsc\PSharp\Source\TestingServices\Runtime\TestingRuntime.cs:line 493
`

On debugging the error, the exception seems to be due to a null dereference in the constructor of the monitor:

`System.TypeInitializationException: The type initializer for 'pingpong.Safety' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at pingpong.Safety..cctor() in C:\Users\t-sumukh\source\repos\vsc\P\Tutorial\PingPong\out\PingPongApp\PingPongApp\pingpong.cs:line 242
   --- End of inner exception stack trace ---
   at pingpong.Safety..ctor() in C:\Users\t-sumukh\source\repos\vsc\P\Tutorial\PingPong\out\PingPongApp\PingPongApp\pingpong.cs:line 239
`

On digging further, I see that the monitor constructor adds the events it observes to `List<string> observes` (the static field of `PMonitor`), but this does not seem to be created. Adding 

`observes = new List<string>();`

allows the testing to go through properly. Thus, the fix involves initializing `PMonitor.observes` appropriately.

I wanted to confirm if this indeed is an issue in the translation to `P#`, and the fix above resolves the issue.

**Comment by ankushdesai** [comment]
Hi Suvam, I will fix this bug in next couple of days and get back to you. Thanks!

**Comment by ankushdesai** [comment]
Fixed this issue of missing initialization. Thanks
