### ISSUE TITLE
Null-dereference during translation to P#

### ISSUE THREAD

**Issue by suvamM** [p-org/P#197]
I coded up a `PingPong` sample, which is a slight variant than the one in the P tutorials. During compilation to `P#`, I get the following error:

`Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Plang.Compiler.DefaultTranslationErrorHandler.IssueError(ParserRuleContext location, String message) in C:\Users\t-sumukh\source\repos\vsc\P\Src\Pc\CompilerCore\DefaultTranslationErrorHandler.cs:line 319
   at Plang.Compiler.DefaultTranslationErrorHandler.MissingDeclaration(ParserRuleContext location, String declarationKind, String missingName) in C:\Users\t-sumukh\source\repos\vsc\P\Src\Pc\CompilerCore\DefaultTranslationErrorHandler.cs:line 66
   at Plang.Compiler.TypeChecker.ModuleExprVisitor.VisitBindExpr(BindExprContext context) in C:\Users\t-sumukh\source\repos\vsc\P\Src\Pc\CompilerCore\TypeChecker\ModuleExprVisitor.cs:line 174
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Plang.Compiler.TypeChecker.ModuleExprVisitor.VisitPrimitiveModuleExpr(PrimitiveModuleExprContext context) in C:\Users\t-sumukh\source\repos\vsc\P\Src\Pc\CompilerCore\TypeChecker\ModuleExprVisitor.cs:line 96
   at Plang.Compiler.PParser.PrimitiveModuleExprContext.Accept[TResult](IParseTreeVisitor`1 visitor) in C:\Users\t-sumukh\source\repos\vsc\P\Src\Pc\CompilerCore\obj\Debug\PParser.cs:line 6039
   at Plang.Compiler.TypeChecker.ModuleSystemDeclarations.PopulateAllModuleExprs(ITranslationErrorHandler handler, Scope globalScope) in C:\Users\t-sumukh\source\repos\vsc\P\Src\Pc\CompilerCore\TypeChecker\ModuleExprVisitor.cs:line 24
   at Plang.Compiler.TypeChecker.Analyzer.AnalyzeCompilationUnit(ITranslationErrorHandler handler, ProgramContext[] programUnits) in C:\Users\t-sumukh\source\repos\vsc\P\Src\Pc\CompilerCore\TypeChecker\Analyzer.cs:line 61
   at Plang.Compiler.Compiler.Compile(ICompilationJob job) in C:\Users\t-sumukh\source\repos\vsc\P\Src\Pc\CompilerCore\Compiler.cs:line 24
   at Plang.Compiler.CommandLine.Main(String[] args) in C:\Users\t-sumukh\source\repos\vsc\P\Src\Pc\CommandLine\CommandLine.cs:line 23`

The necessary files have been attached here: [PingPong.zip](https://github.com/p-org/P/files/2803736/PingPong.zip).

Classifying this as a (possible) bug.

**Comment by ankushdesai** [comment]
This has been fixed now. There was a missing null-reference check when reporting error.
Thanks for catching this!
