### ISSUE TITLE
Internal error "unrecognized type kind (Parameter 'type')" when Target is C

### ISSUE THREAD

**Issue by wutka** [p-org/P#356]
Running pc on Tutorials/ClientServer.pproj with the Target changed to <Target sourcemaps="false">C</Target>
gives the exception below. After some investigation, the type of the PLanguageType variable causing the problem is NamedTupleType, and there is no case to handle that type in the switch statement in the offending method.

Internal Error>:
 unrecognized type kind (Parameter 'type')
<Please report to the P team (p-devs@amazon.com) or create an issue on GitHub, Thanks!>
   at Plang.Compiler.Backend.C.CNameManager.SimplifiedRep(PLanguageType type) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Backend/C/CNameManager.cs:line 166
   at Plang.Compiler.Backend.C.CNameManager.GetNameForType(PLanguageType type) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Backend/C/CNameManager.cs:line 88
   at Plang.Compiler.Backend.C.PrtCodeGeneratorImpl.WriteSourceDecl(TextWriter output, IPDecl decl) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Backend/C/CCodeGenerator.cs:line 294
   at Plang.Compiler.Backend.C.PrtCodeGeneratorImpl.GenerateSourceFile(Scope globalScope) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Backend/C/CCodeGenerator.cs:line 72
   at Plang.Compiler.Backend.C.PrtCodeGeneratorImpl.GenerateCode(ICompilationJob job, Scope globalScope) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Backend/C/CCodeGenerator.cs:line 43
   at Plang.Compiler.Backend.C.CCodeGenerator.GenerateCode(ICompilationJob job, Scope globalScope) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Backend/C/CCodeGenerator.cs:line 22
   at Plang.Compiler.Compiler.Compile(ICompilationJob job) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Compiler.cs:line 38
   at Plang.Compiler.CommandLine.Main(String[] args) in /home/runner/work/P/P/Src/PCompiler/CommandLine/CommandLine.cs:line 25

**Comment by ankushdesai** [comment]
Thanks @wutka, I fixed this bug and added it to the new release.
Note that the C backend does not support `choose` currently. I would request you to replace `choose` with a `$` in these examples. 

I would recommend you to use C# for model checking the protocols modeled in P. If you would like to use generated C code then I would request you to look at some of the other projects that have used P's generated C code:

https://github.com/Drona-Org/Drona

and 

https://github.com/ShivKushwah/PSec

Please let me know if you have any questions.

**Comment by wutka** [comment]
Thank you for the quick turnaround and the explanation about choose!
