### ISSUE TITLE
InvalidCastException bug with named tuples

### ISSUE THREAD

**Issue by pinzaghi** [p-org/P#398]
As discussed in https://github.com/p-org/P/discussions/397 this minimal example trows an `InvalidCastException`, even when the syntax is correct according to the [doc](https://p-org.github.io/P/manual/expressions/#cast).

```
type A = any;
type B = (d1: int, d2: int);

machine BuggyProcess {
    start state Init {
        entry {
            var a : A;
            var b : B;

            a = (1, 2);
            b = a as B;

            print(format("this breaks {0}", b.d2));         
        }
    }
}
```

I created the following test `test TestBug[main = BuggyProcess]: { BuggyProcess };`

The error message:

```
Error: Exception 'System.InvalidCastException' was thrown in PImplementation.BuggyProcess(2) (state 'Init_1', action 'Anon_19'): Unable to cast object of type 'Plang.CSharpRuntime.Values.PrtTuple' to type 'Plang.CSharpRuntime.Values.PrtNamedTuple'.
from location 'Paxos':
The stack trace is:
   at PImplementation.BuggyProcess.Anon_19(Event currentMachine_dequeuedEvent) in /home/inzaghi/workspace/themiscyra/examples/P/Paxos/PGenerated/Paxos.cs:line 1256
   at Microsoft.Coyote.Actors.Actor.InvokeActionAsync(CachedDelegate cachedAction, Event e)

```

**Comment by pinzaghi** [comment]
Finally, it was not a bug, solution in original discussion.
