### ISSUE TITLE
Tutorial build failure on apple M1

### ISSUE THREAD

**Issue by ekexium** [p-org/P#433]
When I was following the [tutorial](https://p-org.github.io/P/getstarted/usingP/) I met the following error.

```
pc -proj:ClientServer.pproj
----------------------------------------
==== Loading project file: ClientServer.pproj
....... includes p file: /Users/eke/code/P/Tutorial/1_ClientServer/PSrc/Server.p
....... includes p file: /Users/eke/code/P/Tutorial/1_ClientServer/PSrc/Client.p
....... includes p file: /Users/eke/code/P/Tutorial/1_ClientServer/PSrc/AbstractBankServer.p
....... includes p file: /Users/eke/code/P/Tutorial/1_ClientServer/PSrc/ClientServerModules.p
....... includes p file: /Users/eke/code/P/Tutorial/1_ClientServer/PSpec/BankBalanceCorrect.p
....... includes p file: /Users/eke/code/P/Tutorial/1_ClientServer/PTst/TestDriver.p
....... includes p file: /Users/eke/code/P/Tutorial/1_ClientServer/PTst/Testscript.p
----------------------------------------
----------------------------------------
Parsing ..
Type checking ...
Code generation ....
Generated ClientServer.cs
----------------------------------------
Compiling ClientServer.csproj ..

<Internal Error>:
 No such file or directory
<Please report to the P team (p-devs@amazon.com) or create an issue on GitHub, Thanks!>
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Plang.Compiler.Backend.CSharp.CSharpCodeCompiler.RunWithOutput(String activeDirectory, String& stdout, String& stderr, String exeName, String[] argumentList) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Backend/CSharp/CSharpCodeCompiler.cs:line 119
   at Plang.Compiler.Backend.CSharp.CSharpCodeCompiler.Compile(ICompilationJob job) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Backend/CSharp/CSharpCodeCompiler.cs:line 80
   at Plang.Compiler.Compiler.Compile(ICompilationJob job) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Compiler.cs:line 53
   at Plang.Compiler.CommandLine.Main(String[] args) in /home/runner/work/P/P/Src/PCompiler/CommandLine/CommandLine.cs:line 25
```

Environment: macOS 12.3.1 on M1.

**Comment by ankushdesai** [comment]
This is super weird. Can you please confirm if you see a ClientServer.csproj file in the folder?

Please delete the generated files and try compiling again.

**Comment by ekexium** [comment]
> Can you please confirm if you see a ClientServer.csproj file in the folder?

Yes.
```
ls
ClientServer.csproj ClientServer.pproj  PGenerated          PSpec               PSrc                PTst                Test.cs
```

> Please delete the generated files and try compiling again.

I think it doesn't work.

> Also, do you see this for other examples in the tutorial as well?

Yes. The same errors in other tutorials.

I tried it in my Linux and it works well.

**Comment by ekexium** [comment]
I think I figured it out. There is no "dotnet" but only "dotnetx64" installed by homebrew. I made a soft link of "dotnet" and it compiled well.
