### ISSUE TITLE
How can compile to other languages from P ( C / Java )

### ISSUE THREAD

**Issue by burakakca** [p-org/P#505]
# C
```
pc PSpec/*.p PSrc/*.p PTst/*.p -generate:C -outputDir:ccc -target:EspressoMachine
----------------------------------------
....... includes p file: /home/burak/Desktop/P/P/Tutorial/3_EspressoMachineBackupBackup/PSpec/Safety.p
....... includes p file: /home/burak/Desktop/P/P/Tutorial/3_EspressoMachineBackupBackup/PSrc/CoffeeMakerControlPanel.p
....... includes p file: /home/burak/Desktop/P/P/Tutorial/3_EspressoMachineBackupBackup/PSrc/CoffeeMaker.p
....... includes p file: /home/burak/Desktop/P/P/Tutorial/3_EspressoMachineBackupBackup/PSrc/EspressoMachineModules.p
....... includes p file: /home/burak/Desktop/P/P/Tutorial/3_EspressoMachineBackupBackup/PTst/TestDrivers.p
....... includes p file: /home/burak/Desktop/P/P/Tutorial/3_EspressoMachineBackupBackup/PTst/TestScripts.p
....... includes p file: /home/burak/Desktop/P/P/Tutorial/3_EspressoMachineBackupBackup/PTst/Users.p
----------------------------------------
----------------------------------------
Parsing ...
Type checking ...
Code generation ...
<Internal Error>:
 choose expression is not supported in C code generation yet!
<Please report to the P team (p-devs@amazon.com) or create an issue on GitHub, Thanks!>
   at Plang.Compiler.Backend.C.PrtCodeGeneratorImpl.WriteExpr(TextWriter output, Function function, IPExpr expr)
   at Plang.Compiler.Backend.C.PrtCodeGeneratorImpl.WriteStmt(TextWriter output, Function function, IPStmt stmt) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Backend/C/CCodeGenerator.cs:line 912
   at Plang.Compiler.Backend.C.PrtCodeGeneratorImpl.WriteFunctionStatements(TextWriter output, Function function, String returnLabelHint) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Backend/C/CCodeGenerator.cs:line 772
   at Plang.Compiler.Backend.C.PrtCodeGeneratorImpl.WriteFunctionBody(TextWriter output, Function function) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Backend/C/CCodeGenerator.cs:line 760
   at Plang.Compiler.Backend.C.PrtCodeGeneratorImpl.WriteFunction(TextWriter output, Function function) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Backend/C/CCodeGenerator.cs:line 412
   at Plang.Compiler.Backend.C.PrtCodeGeneratorImpl.WriteSourceDecl(TextWriter output, IPDecl decl) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Backend/C/CCodeGenerator.cs:line 144
   at Plang.Compiler.Backend.C.PrtCodeGeneratorImpl.WriteSourceDecl(TextWriter output, IPDecl decl) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Backend/C/CCodeGenerator.cs:line 211
   at Plang.Compiler.Backend.C.PrtCodeGeneratorImpl.GenerateSourceFile(Scope globalScope) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Backend/C/CCodeGenerator.cs:line 72
   at Plang.Compiler.Backend.C.PrtCodeGeneratorImpl.GenerateCode(ICompilationJob job, Scope globalScope) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Backend/C/CCodeGenerator.cs:line 43
   at Plang.Compiler.Backend.C.CCodeGenerator.GenerateCode(ICompilationJob job, Scope globalScope) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Backend/C/CCodeGenerator.cs:line 22
   at Plang.Compiler.Compiler.Compile(ICompilationJob job) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Compiler.cs:line 41
   at Plang.Compiler.CommandLine.Main(String[] args) in /home/runner/work/P/P/Src/PCompiler/CommandLine/CommandLine.cs:line 25

```

# Java

```
java --version
openjdk 11.0.14 2022-01-18
OpenJDK Runtime Environment (build 11.0.14+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.14+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
```

```
pc PSpec/*.p PSrc/*.p PTst/*.p -generate:java -outputDir:PGeneratedJava -target:EspressoMachine
----------------------------------------
....... includes p file: /home/burak/Desktop/P/P/Tutorial/3_EspressoMachineBackupBackup/PSpec/Safety.p
....... includes p file: /home/burak/Desktop/P/P/Tutorial/3_EspressoMachineBackupBackup/PSrc/CoffeeMakerControlPanel.p
....... includes p file: /home/burak/Desktop/P/P/Tutorial/3_EspressoMachineBackupBackup/PSrc/CoffeeMaker.p
....... includes p file: /home/burak/Desktop/P/P/Tutorial/3_EspressoMachineBackupBackup/PSrc/EspressoMachineModules.p
....... includes p file: /home/burak/Desktop/P/P/Tutorial/3_EspressoMachineBackupBackup/PTst/TestDrivers.p
....... includes p file: /home/burak/Desktop/P/P/Tutorial/3_EspressoMachineBackupBackup/PTst/TestScripts.p
....... includes p file: /home/burak/Desktop/P/P/Tutorial/3_EspressoMachineBackupBackup/PTst/Users.p
----------------------------------------
----------------------------------------
Parsing ...
Type checking ...
Code generation ...
Generated pom.xml
Generated PTypes.java.
Generated PEvents.java.
Generated PMachines.java.
Generated FFIStubs.txt.
----------------------------------------
Compiling EspressoMachine...
Error:
Java project compilation failed.
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< com.amazon.p:EspressoMachine >--------------------
[INFO] Building EspressoMachine 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for p.runtime:PJavaRuntime:jar:1.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.156 s
[INFO] Finished at: 2022-09-28T16:22:33+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project EspressoMachine: Could not resolve dependencies for project com.amazon.p:EspressoMachine:jar:1.0-SNAPSHOT: Could not find artifact p.runtime:PJavaRuntime:jar:1.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException


WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

```

**Comment by bhencey** [comment]
I've been interested in generating Java from P for a project. I'd be interested in what you learn, and I'll let you know if we learn anything as we trace out how to do this.

**Comment by burakakca** [comment]
@bhencey  I maked compile to java from p

```bash
 mvn -v
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

cd ./Src/PRuntimes/PJavaRuntime
mvn install
```

Now I'm looking how to run compiled example

**Comment by bhencey** [comment]
We haven’t been able to run the jar because the classes for the Pmachines (everything except the monitors) had been “elided”.

**Comment by ankushdesai** [comment]
We have stopped support for code generation in other languages. Most popular usage of P has been design level analysis and verification.
