### ISSUE TITLE
Internal Error: No such file or directory

### ISSUE THREAD

**Issue by hmih** [p-org/P#557]
I'm on a MacOS M1, I followed the installation instructions but have Java installed via `nix`. I tried run the first tutorial - ClientServer and I get the following:

```
[nix-shell:~/fun/formal/P/Tutorial/1_ClientServer]$ pc -proj:ClientServer.pproj
----------------------------------------
==== Loading project file: ClientServer.pproj
....... includes p file: /Users/hristomihaylov/fun/formal/P/Tutorial/1_ClientServer/PSrc/Server.p
....... includes p file: /Users/hristomihaylov/fun/formal/P/Tutorial/1_ClientServer/PSrc/Client.p
....... includes p file: /Users/hristomihaylov/fun/formal/P/Tutorial/1_ClientServer/PSrc/AbstractBankServer.p
....... includes p file: /Users/hristomihaylov/fun/formal/P/Tutorial/1_ClientServer/PSrc/ClientServerModules.p
....... includes p file: /Users/hristomihaylov/fun/formal/P/Tutorial/1_ClientServer/PSpec/BankBalanceCorrect.p
....... includes p file: /Users/hristomihaylov/fun/formal/P/Tutorial/1_ClientServer/PTst/TestDriver.p
....... includes p file: /Users/hristomihaylov/fun/formal/P/Tutorial/1_ClientServer/PTst/Testscript.p
----------------------------------------
----------------------------------------
Parsing ...
Type checking ...
Code generation ...
Generated ClientServer.cs.
----------------------------------------
Compiling ClientServer...
<Internal Error>:
 No such file or directory
<Please report to the P team (p-devs@amazon.com) or create an issue on GitHub, Thanks!>
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Plang.Compiler.Compiler.RunWithOutput(String activeDirectory, String& stdout, String& stderr, String exeName, String[] argumentList) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Compiler.cs:line 142
   at Plang.Compiler.Backend.CSharp.CSharpCodeGenerator.Compile(ICompilationJob job) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Backend/CSharp/CSharpCodeGenerator.cs:line 49
   at Plang.Compiler.Compiler.Compile(ICompilationJob job) in /home/runner/work/P/P/Src/PCompiler/CompilerCore/Compiler.cs:line 56
   at Plang.Compiler.CommandLine.Main(String[] args) in /home/runner/work/P/P/Src/PCompiler/CommandLine/CommandLine.cs:line 25
```

Any clues as to why this is happening?

**Comment by hmih** [comment]
Fix in https://github.com/p-org/P/issues/433
